theme: jekyll-theme-minimal
logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
title: ASADULLAH PRANTO
description: Bookmark this to keep an eye on my project updates!
